### ISSUE TITLE
Using non url safe names as collection names breaks routing

### ISSUE THREAD

**Issue by cyrilselasi** [blackmann/mangobase#1]
### How to Reproduce
1. Create a collection with a name that's not URL safe (eg. Report Cards)
2. Receive a 404 error and a url encoded collection path

### Expectation
1. Collection form should either validate for appropriate collection names
3. Use the collection name provided as a display name and generate a slug

**Comment by blackmann** [comment]
Hi @cyrilselasi 

To remove the _bad_ collection (or rename), you'll find it in the project's `.mangobase` folder in a file: `collections.json`.

You'll have to restart the app
