### ISSUE TITLE
[Feature request] Change port when 3000 is not available

### ISSUE THREAD

**Issue by tsikatawill** [blackmann/mangobase#19]
Currently, Mangobase runs on only port 3000. As this is the case, if there's a server already running on port 3000, Mangobase doesn't run.
Would be nice to have the port change automactically if it's already in use

NB: 
- should only work in dev mode

**Comment by blackmann** [comment]
If the port conflicts another port, you can edit your `src/index.ts` to change the default PORT.

Or close the conflicting app.
